version: 2.1

# CircleCI orbs for React Native and Android
orbs:
  android: circleci/android@2.3.0
  node: circleci/node@5.1.0

jobs:
  # Install React Native dependencies
  install-dependencies:
    executor:
      name: node/default
      tag: '18.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package-lock.json

  # Build Android APK
  build-android-apk:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.07.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      
      # Setup Java 17
      - run:
          name: Set Java Version
          command: |
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      
      # Restore Android dependencies cache
      - android/restore-gradle-cache
      
      # Make gradlew executable
      - run:
          name: Make Gradlew Executable
          command: chmod +x android/gradlew
      
      # Install React Native dependencies if not cached
      - run:
          name: Install Dependencies
          command: npm install
      
      # Clean previous builds
      - run:
          name: Clean Build
          command: cd android && ./gradlew clean
      
      # Build Debug APK
      - run:
          name: Build Debug APK
          command: cd android && ./gradlew assembleDebug
      
      # Build Release APK (unsigned)
      - run:
          name: Build Release APK
          command: cd android && ./gradlew assembleRelease
      
      # Copy APK files to artifacts directory
      - run:
          name: Copy APK Files
          command: |
            mkdir -p /tmp/apk-artifacts
            find android -name "*.apk" -exec cp {} /tmp/apk-artifacts/ \;
            ls -la /tmp/apk-artifacts/
      
      # Store APK files as artifacts
      - store_artifacts:
          path: /tmp/apk-artifacts
          destination: apk-files
      
      # Save Gradle cache
      - android/save-gradle-cache

workflows:
  react-native-build:
    jobs:
      - install-dependencies
      - build-android-apk:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - main_budget
